### ISSUE TITLE
Suppress removal of spaces between Japanese characters

### ISSUE THREAD

**Issue by feddyfedfed** [ikegami-yukino/neologdn#10]
Is it possible to do the [title]?  I noticed that it always removes the space for Japanese characters but for my case I need to preserve it.  Thank you very much.

**Comment by ikegami-yukino** [comment]
I added the option to suppress removal of spaces between Japanese characters.
Please try `neologdn.normalize(text, remove_space=False)`

**Comment by feddyfedfed** [comment]
Thank you so much, it's working now
