### ISSUE TITLE
Unable to import under anaconda3 in pyenv 

### ISSUE THREAD

**Issue by shuntaroy** [ikegami-yukino/neologdn#4]
I installed your package via gcc-5 (homebrew; Mac OS X 10.11.4) through following command, because the Apple's compiler is outdated.

```
$ env CC=/usr/local/bin/gcc-5 pip install neologdn
```

After that, I tried to import the package, but I faced to en error like this.

```
In [1]: import neologdn
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-500d73366729> in <module>()
----> 1 import neologdn

ImportError: dlopen(/Users/shuntaroy/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/neologdn.cpython-35m-darwin.so, 2): Symbol not found: __ZNKSt8__detail20_Prime_rehash_policy14_M_need_rehashEmmm
  Referenced from: /Users/shuntaroy/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/neologdn.cpython-35m-darwin.so
  Expected in: dynamic lookup
```

My Python version is `Python 3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55)`, which is installed in pyenv.

I'm not aware of Clang nor Cython.
I would appreciate if you could give me an advice.

Thank you.

**Comment by ikegami-yukino** [comment]
Thanks for error reporting.

Unfortunately I am not really familiar with pyenv, anaconda.
What will happen by using other compilers instead of gcc-5?

**Comment by shuntaroy** [comment]
Sorry for late reply. 
Because I have little knowledge of C++ and unfortunately don't have enough time this week, I need some time to investigate it. 
However, I first tried gcc v4.2 or v4.3 or so, which come from OSX command line tools.
That didn't work and said unordered map is not available. 
Sorry for ambiguous report due to leaving my desk, but I think I should reply sooner.

**Comment by ikegami-yukino** [comment]
On my computer (OSX 10.10), gcc-4.2.1 works well.

```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Sorry for no idea about this problem.

**Comment by Kensuke-Mitsuzawa** [comment]
I also use anaconda(anaconda3-4.0.0) and I encountered the same issue under gcc 4.2.1
Now, I made updated gcc version into gcc 5.4.0, and the issue went away.

for your information, this is gcc in my environment.

```
(root) MacBook-Pro% gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@5/5.4.0/bin/../libexec/gcc/x86_64-apple-darwin15.5.0/5.4.0/lto-wrapper
Target: x86_64-apple-darwin15.5.0
Configured with: ../configure --build=x86_64-apple-darwin15.5.0 --prefix=/usr/local/Cellar/gcc5/5.4.0 --libdir=/usr/local/Cellar/gcc5/5.4.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl014 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc5 5.4.0' --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 5.4.0 (Homebrew gcc5 5.4.0) 
```

**Comment by shuntaroy** [comment]
Since I quit using neither anaconda nor pyenv, this issue no longer applies to me. Although I am not sure anyone else still suffering from this issue, I think this could be closed for the time being. Thanks
